# Air configuration for StaffFind backend
# Air will watch file changes and automatically restart the server

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Just plain old shell command. You could use `make` as well.
  cmd = "go build -o ./tmp/main ./cmd/server"
  # Binary file yields from `cmd`.
  bin = "tmp/main"
  # Customize binary, can setup environment variables when run your app.
  # Environment variables are loaded from .env file by godotenv in Go code
  full_bin = "./tmp/main"
  # Watch these filename extensions.
  include_ext = ["go", "tpl", "tmpl", "html", "sql", "yaml", "yml"]
  # Ignore these filename extensions or directories.
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules", ".git", ".vscode", ".idea"]
  # Watch these directories if you specified.
  include_dir = []
  # Exclude files.
  exclude_file = []
  # Exclude specific regular expressions.
  exclude_regex = ["_test.go"]
  # Exclude unchanged files.
  exclude_unchanged = false
  # Follow symlink for directories
  follow_symlink = false
  # This log file places in your tmp_dir.
  log = "errors.log"
  # Poll files for changes instead of using fsnotify
  poll = false
  # Poll interval (defaults to the minimum interval of 500ms)
  poll_interval = 0
  # Delay time after execution of each commands
  delay = 0
  # Stop running old binary when build errors occur.
  stop_on_root = false
  # Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = false
  # Delay after sending Interrupt signal
  kill_delay = "0s"
  # Rerun binary or not
  rerun = false
  # Delay after each executions
  rerun_delay = 500
  # Add additional arguments when running binary (bin/full_bin). Will run './tmp/main hello world'.
  args_bin = []
  # Show log time
  show_log_time = false
  # Show log in different colors
  log_color = true
  # Dont show logs from Air
  hide_log_output = false

[color]
  # Customize each part's color. If no color found, use the raw app log.
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  # Show log time
  time = false
  # Only show main log
  main_only = false

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true

[screen]
  # Clear screen on each build
  clear_on_rebuild = true
  # Keep scroll on rebuild
  keep_scroll = true
