# Employee and Skill Management Queries

queries:
  # Employee-related queries
  employees:
    get_all_employees:
      description: "Retrieve all employees with their basic information"
      category: "employees"
      operation: "select"
      parameters: []
      tags: ["employees", "list", "basic"]
      sql_file: "employees.sql"
      
    get_employee_by_id:
      description: "Retrieve a specific employee by ID"
      category: "employees"
      operation: "select"
      parameters:
        - name: "id"
          type: "int"
          required: true
          description: "Employee ID"
      tags: ["employees", "single", "by_id"]
      sql_file: "employees.sql"
      
    create_employee:
      description: "Create a new employee record"
      category: "employees"
      operation: "insert"
      parameters:
        - name: "name"
          type: "string"
          required: true
          description: "Employee full name"
        - name: "email"
          type: "string"
          required: true
          description: "Employee email address"
        - name: "department"
          type: "string"
          required: false
          description: "Employee department"
        - name: "level"
          type: "string"
          required: false
          description: "Employee experience level"
        - name: "location"
          type: "string"
          required: false
          description: "Employee location"
        - name: "bio"
          type: "string"
          required: false
          description: "Employee biography"
        - name: "current_project"
          type: "string"
          required: false
          description: "Employee current project"
      tags: ["employees", "create", "insert"]
      sql_file: "employees.sql"
      
    update_employee:
      description: "Update an existing employee record"
      category: "employees"
      operation: "update"
      parameters:
        - name: "name"
          type: "string"
          required: true
          description: "Employee full name"
        - name: "email"
          type: "string"
          required: true
          description: "Employee email address"
        - name: "department"
          type: "string"
          required: false
          description: "Employee department"
        - name: "level"
          type: "string"
          required: false
          description: "Employee experience level"
        - name: "location"
          type: "string"
          required: false
          description: "Employee location"
        - name: "bio"
          type: "string"
          required: false
          description: "Employee biography"
        - name: "current_project"
          type: "string"
          required: false
          description: "Employee current project"
        - name: "id"
          type: "int"
          required: true
          description: "Employee ID to update"
      tags: ["employees", "update", "modify"]
      sql_file: "employees.sql"
      
    delete_employee:
      description: "Delete an employee record"
      category: "employees"
      operation: "delete"
      parameters:
        - name: "id"
          type: "int"
          required: true
          description: "Employee ID to delete"
      tags: ["employees", "delete", "remove"]
      sql_file: "employees.sql"
      
    get_employee_skills:
      description: "Get all skills for a specific employee"
      category: "employees"
      operation: "select"
      parameters:
        - name: "employee_id"
          type: "int"
          required: true
          description: "Employee ID"
      tags: ["employees", "skills", "relationships"]
      sql_file: "employees.sql"
      
    add_employee_skill:
      description: "Add a skill relationship to an employee"
      category: "employees"
      operation: "insert"
      parameters:
        - name: "employee_id"
          type: "int"
          required: true
          description: "Employee ID"
        - name: "skill_id"
          type: "int"
          required: true
          description: "Skill ID"
        - name: "proficiency_level"
          type: "int"
          required: true
          description: "Proficiency level (1-5)"
        - name: "years_experience"
          type: "float"
          required: true
          description: "Years of experience"
      tags: ["employees", "skills", "relationships"]
      sql_file: "employees.sql"
      
    remove_employee_skills:
      description: "Remove all skill relationships for an employee"
      category: "employees"
      operation: "delete"
      parameters:
        - name: "employee_id"
          type: "int"
          required: true
          description: "Employee ID"
      tags: ["employees", "skills", "cleanup"]
      sql_file: "employees.sql"

  # Skill-related queries
  skills:
    get_all_skills:
      description: "Retrieve all available skills"
      category: "skills"
      operation: "select"
      parameters: []
      tags: ["skills", "list", "all"]
      sql_file: "skills.sql"
      
    get_skill_by_id:
      description: "Retrieve a skill by ID"
      category: "skills"
      operation: "select"
      parameters:
        - name: "id"
          type: "int"
          required: true
          description: "Skill ID"
      tags: ["skills", "single", "by_id"]
      sql_file: "skills.sql"
      
    get_skill_by_name:
      description: "Retrieve a skill by name"
      category: "skills"
      operation: "select"
      parameters:
        - name: "name"
          type: "string"
          required: true
          description: "Skill name"
      tags: ["skills", "single", "by_name"]
      sql_file: "skills.sql"
      
    create_skill:
      description: "Create a new skill"
      category: "skills"
      operation: "insert"
      parameters:
        - name: "name"
          type: "string"
          required: true
          description: "Skill name"
        - name: "category"
          type: "string"
          required: false
          description: "Skill category"
      tags: ["skills", "create", "insert"]
      sql_file: "skills.sql"
      
    update_skill:
      description: "Update an existing skill"
      category: "skills"
      operation: "update"
      parameters:
        - name: "name"
          type: "string"
          required: true
          description: "Skill name"
        - name: "category"
          type: "string"
          required: false
          description: "Skill category"
        - name: "id"
          type: "int"
          required: true
          description: "Skill ID to update"
      tags: ["skills", "update", "modify"]
      sql_file: "skills.sql"
      
    delete_skill:
      description: "Delete a skill"
      category: "skills"
      operation: "delete"
      parameters:
        - name: "id"
          type: "int"
          required: true
          description: "Skill ID to delete"
      tags: ["skills", "delete", "remove"]
      sql_file: "skills.sql"
