# File Upload and Management Queries

queries:
  # Uploaded File-related queries
  uploaded_files:
    create_uploaded_file:
      description: "Create a new uploaded file record"
      category: "uploaded_files"
      operation: "insert"
      parameters:
        - name: "filename"
          type: "string"
          required: true
          description: "File name"
        - name: "original_filename"
          type: "string"
          required: true
          description: "Original file name"
        - name: "file_path"
          type: "string"
          required: true
          description: "File path"
        - name: "file_size"
          type: "int64"
          required: true
          description: "File size in bytes"
        - name: "content_type"
          type: "string"
          required: true
          description: "Content type"
        - name: "file_hash"
          type: "string"
          required: true
          description: "File hash"
        - name: "upload_type"
          type: "string"
          required: true
          description: "Upload type"
        - name: "status"
          type: "string"
          required: true
          description: "File status"
        - name: "uploaded_by"
          type: "int"
          required: false
          description: "User ID who uploaded"
        - name: "employee_id"
          type: "int"
          required: false
          description: "Employee ID"
        - name: "metadata"
          type: "json"
          required: false
          description: "File metadata as JSON"
      tags: ["uploaded_files", "create", "insert"]
      sql_file: "uploaded_files.sql"
      
    get_uploaded_file_by_id:
      description: "Get uploaded file by ID"
      category: "uploaded_files"
      operation: "select"
      parameters:
        - name: "id"
          type: "int"
          required: true
          description: "File ID"
      tags: ["uploaded_files", "single", "by_id"]
      sql_file: "uploaded_files.sql"
      
    get_uploaded_file_by_filename:
      description: "Get uploaded file by filename"
      category: "uploaded_files"
      operation: "select"
      parameters:
        - name: "filename"
          type: "string"
          required: true
          description: "File name"
      tags: ["uploaded_files", "single", "by_filename"]
      sql_file: "uploaded_files.sql"
      
    get_uploaded_file_by_hash:
      description: "Get uploaded file by hash"
      category: "uploaded_files"
      operation: "select"
      parameters:
        - name: "file_hash"
          type: "string"
          required: true
          description: "File hash"
      tags: ["uploaded_files", "single", "by_hash"]
      sql_file: "uploaded_files.sql"
      
    delete_uploaded_file:
      description: "Delete uploaded file permanently"
      category: "uploaded_files"
      operation: "delete"
      parameters:
        - name: "id"
          type: "int"
          required: true
          description: "File ID to delete"
      tags: ["uploaded_files", "delete", "permanent"]
      sql_file: "uploaded_files.sql"
      
    soft_delete_uploaded_file:
      description: "Soft delete uploaded file"
      category: "uploaded_files"
      operation: "update"
      parameters:
        - name: "id"
          type: "int"
          required: true
          description: "File ID to soft delete"
      tags: ["uploaded_files", "delete", "soft"]
      sql_file: "uploaded_files.sql"
      
    cleanup_old_files:
      description: "Clean up old deleted files"
      category: "uploaded_files"
      operation: "delete"
      parameters:
        - name: "older_than"
          type: "timestamp"
          required: true
          description: "Delete files older than this timestamp"
      tags: ["uploaded_files", "cleanup", "maintenance"]
      sql_file: "uploaded_files.sql"
